### PR TITLE
Task 8 (Docker. AWS Elastic Beanstalk)

### PR DESCRIPTION
**Pull request by Yuliya-soul**
EVALUATION CRITERIA:
1 - Dockerfile is prepared, image is building. Image size is minimised to be less than 500 MB.
2 - Dockerfile is optimized. Files that change more often and commands that depend on them should be included later, files and commands that change less should be at the top.
3 - Folders are added to .dockerignore, with explanations. At least 2 big directories should be excluded from build context. Elastic Beanstalk application is initialized.
4 - Environment is created and the app is deployed to the AWS cloud. You must provide a link to your GitHub repo with Cart API service or PR with created Dockerfile and related configurations.
5 - FE application is updated with Cart API endpoint. You must provide a PR with updates in your FE repository and OPTIONALLY link to deployed front-end app which makes proper API calls to your Cart service.
Total:5
we added at .dockerignore:
dist - is build inside dockerfile
test -  tests are redundant in production 
node_modules - we make nom install in dockerfile
git is not used inside dockerfile

CloudFront Distribution:https://d3hzy7osffhiya.cloudfront.net/
Cart API service: 'http://yuliya-soul.us-east-1.elasticbeanstalk.com/'
Dockerfile and related configurations:
https://github.com/Yuliya-soul/aws-shop-fe/blob/task-8/rs-cart-api/Dockerfile, 
https://github.com/Yuliya-soul/aws-shop-fe/blob/task-8/rs-cart-api/.dockerignore

### CODE REVIEW

**Comment by unfalse** [comment]
Тут надо было добавить всего 2 файла, откуда 64 ? )) Рефакторинг можно было отдельной веткой. И cart-api влить сразу в main.

**Comment by Yuliya-soul** [comment]
Prerequisites
The task is a continuation of Homework 7 and should be done in the same front-end repo
Create your own copy of Cart API template repository
AWS EB CLI must be installed
Docker must be installed

According tp the task we make dockerfile from https://github.com/boale/rs-cart-api, which we copy to our repo and task-1-task-7 branches where not merged
I provided link:
Dockerfile and related configurations:
https://github.com/Yuliya-soul/aws-shop-fe/blob/task-8/rs-cart-api/Dockerfile,
https://github.com/Yuliya-soul/aws-shop-fe/blob/task-8/rs-cart-api/.dockerignore

**Comment by unfalse** [comment]
> Тут надо было добавить всего 2 файла, откуда 64 ? )) Рефакторинг можно было отдельной веткой. И cart-api влить сразу в main.

This notice doesn't affect the final evaluation.

**Comment by unfalse** [comment]
CloudFront doesn't work

image

image

Please fix

**Comment by Yuliya-soul** [comment]
Cart API service: 'http://yuliya-soul.us-east-1.elasticbeanstalk.com/'
this link was added to fe .
to make fe work from task 7 you should add password  authorization_token WVVMSVlBX1NPVUw6VEVTVF9QQVNTV09SRA==
at your browser at Local Storage
2021-09-28_19h54_49
But all these refers to tak 7.
All things that should work at task 8:
CloudFront Distribution:https://d3hzy7osffhiya.cloudfront.net/
Cart API service: 'http://yuliya-soul.us-east-1.elasticbeanstalk.com/'
Dockerfile and related configurations:
https://github.com/Yuliya-soul/aws-shop-fe/blob/task-8/rs-cart-api/Dockerfile,
https://github.com/Yuliya-soul/aws-shop-fe/blob/task-8/rs-cart-api/.dockerignore
And we should not provide work of https://github.com/boale/rs-cart-api just add link to it from eb.

**Comment by Yuliya-soul** [comment]
Btw EVALUATION CRITERIA at task 8 doesn't include number of folders at repo or code quality

**Comment by Yuliya-soul** [comment]
' There are no products on main page' I swithed off rds because my fee tier expired

**Comment by Yuliya-soul** [comment]
'Docker image is less than 500 MB but I can't check if cart service is working properly cause I can't add any product into cart' actually because all of us have the same repo that we put at dockerfile https://github.com/boale/rs-cart-api you can put instead of your dockerfile mine , build and see actual size.

**Comment by ReshetovItsMe** [comment]
согласен с @unfalse, можно было просто форкнуть репо cart-api и там все сделать. на оценку это не влияет, просто note))

**Comment by Yuliya-soul** [comment]
Task 8 (Docker. AWS Elastic Beanstalk)
After Lecture 8 "Docker. AWS Elastic Beanstalk"

Prerequisites
The task is a continuation of Homework 7 and should be done in the same front-end repo
Create your own copy of Cart API template repository

any questions?

**Comment by unfalse** [comment]
> Task 8 (Docker. AWS Elastic Beanstalk) After Lecture 8 "Docker. AWS Elastic Beanstalk"
> 
> Prerequisites The task is a continuation of Homework 7 and should be done in the same front-end repo Create your own copy of Cart API template repository
> 
> any questions?

К тому что это в репозитории фронта, у меня никаких вопросов нет, благо в задании всё равно забыли написать что надо копировать репозиторий в отдельную папку внутри репозитория фронта, поэтому видимо каждый понял по-своему :)) Я уже видел у двух людей отдельные репы для cart-api.
Я в первом комментарии писал что перед созданием ПР было бы неплохо сразу влить в main файлы из скопированного boale/cart-api, чтобы в итоговом ПР не было десятков измененных файлов, а только 2-3.
Всё-таки у всех этот cart-api один и тот же и ревьювить одни и те же файлы нет смысла.
Ну и плюс я заметил что старые файлы фронта изменены и назвал это рефакторингом и предлагал также сразу влить в main, потому что по сути к заданию он не относился.
Просто я вижу что в итоге меня никто не понял))
На оценку это никак не влияет, просто хотел объясниться.
Я уже проходил один курс и у меня как-то раз вышло что в ПР попало около сотни файлов и ревьюверу было сложно понять что там конкретно относится к заданию, а что является мелкими правками. Я тогда влил эти правки сразу и пересоздавал ПР. Тут я ничего не прошу менять, просто это скорее пожелание.

**Comment by Yuliya-soul** [comment]
it was possible to merge in main but for this review was needed to check only 3 links in pr and nothing more .

**Pull request merged**
